### PR TITLE
Add trailing slash when looking for directories

### LINKED ISSUE #22: Deterministic completion for directories only adds a trailing slash after second Tab press
Suppose I want to `cd` to `.config/gedit`. With usual bash, I do:
```
$ cd .co<TAB>
```
which completes it to
```
$ cd .config/
```
and I can type the rest.

With partial path completion enabled, I do
```
$ cd .co<TAB>
```
which completes it to
```
$ cd .config
```
and then only a second Tab keypress completes it to
```
$ cd .config/
```

Demo: https://asciinema.org/a/549122

### PR DESCRIPTION
**Pull request by kolayne**
Fixes #22 (although, I'm not sure this is the only place that should be updated)

### CODE REVIEW

**Comment by sio** [comment]
I've checked that by default bash behaves as you decribed here and in the issue. Thank you for reporting this.

This PR requires some extra work before it's ready to be merged. Please check failing CI runs on Linux (ignore macOS and FreeBSD for now because they require [custom setup](https://github.com/sio/bash-complete-partial-path/tree/master/tests#cirrus-ci-integration-for-forks-of-this-repository))

From a brief look at failed test cases here are the things that need to be fixed:

- `file` variable leaks into global scope
- Many test cases need to be updated because they were expecting output without a trailing slash. This will require quite a lot of boring work because blanket-appending slashes to every failed test data could hide some errors (e.g. we must not append slash to paths that are not directories)
- Some changed test outputs introduce not only new slash suffix, but also change the prefix. It's hard to tell if this is acceptable without interactive manual testing. My intuition says it's an error, but I'm not sure. E.g. this snippet in CI output:

```diff
 - {'usr/share/', 'usr/somefile'}
 + {'somefile', 'share/'}
```

Looking from a higher level though... I'm not sure I like the first part of the diff. "FIXME" is kinda a red flag right away, but even without that a duplicated `compgen` call for a single completion plus a throwaway SUBDIRS array do not seem like a neat solution.

```bash
        if [[ "_$ACTION" == "_directory" ]]
        then
            OPTION="dirnames"
        else
            OPTION="filenames"
        fi
```

How about leaving this section largely intact and setting all compgen keys there? (`-o dirnames -S /` for directories and `-o filenames` for regular files). We could call compgen just once then.

**Comment by kolayne** [comment]
> * Many test cases need to be updated because they were expecting output without a trailing slash. This will require quite a lot of boring work because blanket-appending slashes to every failed test data could hide some errors (e.g. we must not append slash to paths that are not directories)

:+1: 

> * Some changed test outputs introduce not only new slash suffix, but also change the prefix. It's hard to tell if this is acceptable without interactive manual testing. My intuition says it's an error, but I'm not sure.

I have noticed that too, but I failed to figure out when this case appears. Even while manually testing the `master` version of it, I haven't run into a situation where the prefix of the completion was omitted...

> "FIXME" is kinda a red flag right away,

Omg, sorry, I forgot to fix that before opening a PR

> a duplicated `compgen` call for a single completion plus a throwaway SUBDIRS array do not seem like a neat solution.
>
> How about leaving this section largely intact and setting all compgen keys there? (`-o dirnames -S /` for directories and `-o filenames` for regular files). We could call compgen just once then.

This does sound better than the current solution. However, it doesn't seem to work on my machine:
```
nikolay@KoLin:~$ compgen -o dirnames -S / D
Desktop
Docs
Downloads
nikolay@KoLin:~$ 
```

**Comment by sio** [comment]
> This does sound better than the current solution. However, it doesn't seem to work on my machine: `$ compgen -o dirnames -S / D`

That's weird. Doesn't work for me too.

Anyways, the idea was to provide all arguments in one variable and then call `compgen $ARGS "$INPUT"` once. The fact that ARGS will have to be `-S/ -d` instead of `-S/ -o dirnames` is an implementation detail 🙂

**Comment by kolayne** [comment]
Oops, that's accidental.

I don't think I'll ever get back to this, though. Anyone is welcome to use the code as the base for a better implementation, if needed.

**Pull request closed without merging**
